FROM python:3.13
ENTRYPOINT ["source"]
CMD ["/.venv/bin/activate"]

RUN ["python3", "pip", "install", "-r", "requirements.txt"]
RUN ["python3", "-m", "spacy", "download", "en_core_web_lg"]
WORKDIR "webpage"
RUN ["python3", "-m", "flask", "--app", "setup", "run"]


